netCore2/DreamPlace.Web.Beepbooking/Models/Order.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DreamPlace.Web.Beepbooking.Models
{
    public class Order
    {
		[Key]
		public int Id { get; set; }
		public DateTime Start { get; set; }
		public DateTime End { get; set; }
		public int CarTypeId { get; set; }
		public int CityId { get; set; }
	    public int StatusId { get; set; }
		public string UserId { get; set; }
	    public string ExecuterId { get; set; }
	    public string Message { get; set; }

		[ForeignKey("UserId")]
		public ApplicationUser User { get; set; }
	    [ForeignKey("ExecuterId")]
	    public ApplicationUser Executer { get; set; }

	    [ForeignKey("StatusId")]
		public Status Status { get; set; }
	    [ForeignKey("CarTypeId")]
		public CarType CarType { get; set; }
	    [ForeignKey("CityId")]
		public City City { get; set; }


		[NotMapped]
		public SelectList CitiesView { get; set; }
	    [NotMapped]
		public SelectList CarTypesView { get; set; }

	}
}

netCore2/DreamPlace.Web.Beepbooking/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DreamPlace.Web.Beepbooking.Data;
using DreamPlace.Web.Beepbooking.Models;
using DreamPlace.Web.Beepbooking.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace DreamPlace.Web.Beepbooking.Controllers
{
	[Authorize(Roles = "user")]
	public class OrdersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private IUserService _userService;

		public OrdersController(ApplicationDbContext context,
			IUserService userService)
		{
			_userService = userService;
			_context = context;
		}

		[Authorize(Roles = "user")]
		public async Task<IActionResult> MyOrders()
		{
			var idCurUser = _userService.GetCurrentUserId();
			var orders = this.GetForUser(idCurUser)
				.Include(el => el.City);

			return View(await orders.ToListAsync());
		}
		
		[HttpPost]
		public IActionResult Accept(int id)
		{
			var idCurUser = _userService.GetCurrentUserId();
			Order order = _context.Orders.FirstOrDefault(el => el.Id == id);
			order.ExecuterId = idCurUser;
			
			_context.Orders.Update(order);

			return Ok();
		}

		[Authorize(Roles = "user")]
		public async Task<IActionResult> Index()
		{
			string idCurUser = _userService.GetCurrentUserId();
			var orders = GetWithoutForUser(idCurUser)
				.Include(el => el.User)
				.Include(el => el.CarType)
				.Include(el => el.City);

			return View(await orders.ToListAsync());
		}

		private IQueryable<Order> GetForUser(string userId)
		{
			return _context.Orders.Where(el => el.UserId == userId);
		}

		private IQueryable<Order> GetWithoutForUser(string userId)
		{
			return _context.Orders.Where(el => el.UserId != userId);
		}

		// GET: Orders/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.SingleOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		[Authorize(Roles = "user")]
		public IActionResult Create()
		{
			Order order = GetOrdersView();
			return View(order);
		}

		private Order GetOrdersView()
		{
			List<City> cities;
			List<CarType> types;
			using (_context)
			{
				cities = _context.Cities.ToList();
				types = _context.CarTypes.ToList();
			}

			var order = new Order
			{
				CitiesView = new SelectList(cities, "Id", "Name"),
				CarTypesView = new SelectList(types, "Id", "Name"),
			};
			return order;
		}

		// POST: Orders/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Order order)
		{
			if (ModelState.IsValid)
			{
				order.StatusId = 1;
				order.UserId = _userService.GetUser().Id;
				_context.Add(order);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(order);
		}

		// GET: Orders/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders.SingleOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}
			return View(order);
		}

		// POST: Orders/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Start,End")] Order order)
		{
			if (id != order.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(order);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!OrderExists(order.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(order);
		}

		// GET: Orders/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var order = await _context.Orders
				.SingleOrDefaultAsync(m => m.Id == id);
			if (order == null)
			{
				return NotFound();
			}

			return View(order);
		}

		// POST: Orders/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var order = await _context.Orders.SingleOrDefaultAsync(m => m.Id == id);
			_context.Orders.Remove(order);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool OrderExists(int id)
		{
			return _context.Orders.Any(e => e.Id == id);
		}
	}
}

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/Create.cshtml
@model DreamPlace.Web.Beepbooking.Models.Order
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}
@*<h2>Create</h2>

	<h4>Order</h4>
	<hr />
	<div class="row">
		<div class="col-md-4">
			<form asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Start" class="control-label"></label>
					<input asp-for="Start" class="form-control" />
					<span asp-validation-for="Start" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="End" class="control-label"></label>
					<input asp-for="End" class="form-control" />
					<span asp-validation-for="End" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-default" />
				</div>
			</form>
		</div>
	</div>*@
<section id="my_dv">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 npd">
				<form asp-action="Create">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<h2>Создать заказ</h2>
					<h3>Выберите тип автомобиля</h3>
					<div class="col-sm-6 npd">
						<select  asp-for="CityId" asp-items="Model.CitiesView"></select>
					</div>
					@*<div class="col-sm-6 npd">
							<select>
								<option>Бюджетный вариант</option>
								<option>Бюджетный вариант</option>
								<option>Бюджетный вариант</option>
							</select>
						</div>*@
					<div style="clear: both;"></div>
					<h3>Выберите город</h3>
					<div class="col-sm-6 npd">
						<select asp-for="CarTypeId" asp-items="Model.CarTypesView"></select>
					</div>
					@*<select>
							<option>Бюджетный вариант</option>
							<option>Бюджетный вариант</option>
							<option>Бюджетный вариант</option>
						</select>*@
					<h3>На какие даты планируете аренду?</h3>
					<div class="col-sm-11 npd">
						<div class='input-group date' id='datestart'>
							<input asp-for="Start" type='text' class="form-control" />
							<span class="input-group-addon">
							</span>
						</div>
						<div class='input-group date' id='dateend'>
							<input asp-for="End" type='text' class="form-control" />
							<span class="input-group-addon">
							</span>
						</div>
						<style>
							.date {
								float: left;
								width: 50%;
								margin: 0;
							}

								.date input {
									width: 95% !important;
								}

							.input-group-addon {
								display: none;
							}
						</style>
					</div>
					<div class="col-sm-1 npd" id="date">
						<input type="text" style="text-align: center;">
					</div>
					<button type="submit" class="aqua">Найти авто</button>
					<button class="white">Отмена</button>
				</form>

				<script type="text/javascript">
					$(function () {
						$('#datestart, #dateend').datepicker({
							format: 'mm/dd/yyyy',
							language: 'ru'
						});
					});
					$('input').change(function () {
						var datestart = parseInt($('#datestart input').val());
						var dateend = parseInt($('#dateend input').val());
						var dayslays = dateend - datestart;
						if (!dayslays || dayslays < 0) { $('#date input').val(''); }
						else {
							$('#date input').val(dayslays + ' дней');
						}
					});
				</script>

			</div>
		</div>
	</div>
</section>

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/Delete.cshtml
@model DreamPlace.Web.Beepbooking.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/Details.cshtml
@model DreamPlace.Web.Beepbooking.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/Edit.cshtml
@model DreamPlace.Web.Beepbooking.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}

<h2>Edit</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/Index.cshtml
@model IEnumerable<DreamPlace.Web.Beepbooking.Models.Order>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}

<section id="my_dv">
<div class="container">
<div class="row">
	<h2>Новые заказы</h2>
	<h3>Обрабатывайте быстро новые заказы</h3>
	
	@{
		foreach (var item in Model)
		{
			<form asp-controller="Orders" asp-action="Accept" method="post" class="dv offer col-md-4 col-sm-6">
				<img src="img/ava2.png" alt="">
				<input id="Id" name="Id" type="hidden" value="@item.Id"/>
				<h1>@item.User.UserName</h1>
				<h3>@item.City.Name</h3>
				<h2>
					с @item.Start.ToShortDateString()
					до @item.End.ToShortDateString()
					(@item.End.Subtract(item.Start).Subtract(new TimeSpan(1, 0, 0, 0)).Days дней)<br>Самый дешевый вариант авто<br>Нужно срочно!!!
				</h2>
				<button type="submit" class="aqua">Принять</button>
				<button class="white">Отклонить</button>
			</form>
		}
	}
</div>
</div>
</section>

@*<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Start)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.End)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@

netCore2/DreamPlace.Web.Beepbooking/Views/Orders/MyOrders.cshtml
@model IEnumerable<DreamPlace.Web.Beepbooking.Models.Order>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_AuthedLayout.cshtml";
}

<section id="my_dv">
	<div class="container">
		<div class="row">
			<h2>Новые заказы</h2>
			<h3>Обрабатывайте быстро новые заказы</h3>

			@{
				foreach (var item in Model)
				{
					<div class="dv">
						<img src="img/car_min2.png" alt="" />
						<h1>Аренда авто</h1>
						<h2>
							C @item.Start.ToShortDateString() до @item.End.ToShortDateString()
							<span>(@item.End.Subtract(item.Start).Subtract(new TimeSpan(1, 0, 0, 0)).Days дней)</span>
							<a href="javascript:void(0);">Удалить</a>
						</h2>
						<h3><img src="img/loc.png" alt="">@item.City.Name</h3>
						<div style="clear:both;"></div>
					</div>
				}
			}
		</div>
	</div>
</section>